/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.benary.vocab;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author benaryorg
 */
public class Fenster extends javax.swing.JFrame
{

    /**
     * Creates new form fenster
     */
    public Fenster()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        MenuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        Menu_File_Open = new javax.swing.JMenuItem();
        Menu_File_Save = new javax.swing.JMenuItem();
        Menu_Vocab_Add = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vokabellernprogramm by benaryorg");

        Panel.setLayout(new java.awt.BorderLayout());

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Englisch", "Deutsch"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        Panel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Panel, java.awt.BorderLayout.CENTER);

        Menu.setText("Datei");

        Menu_File_Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Menu_File_Open.setText("Öffnen");
        Menu_File_Open.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Menu_File_OpenActionPerformed(evt);
            }
        });
        Menu.add(Menu_File_Open);

        Menu_File_Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Menu_File_Save.setText("Speichern");
        Menu_File_Save.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Menu_File_SaveActionPerformed(evt);
            }
        });
        Menu.add(Menu_File_Save);

        Menu_Vocab_Add.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        Menu_Vocab_Add.setText("Hinzufügen");
        Menu_Vocab_Add.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Menu_Vocab_AddActionPerformed(evt);
            }
        });
        Menu.add(Menu_Vocab_Add);

        MenuBar.add(Menu);

        setJMenuBar(MenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Menu_File_OpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Menu_File_OpenActionPerformed
    {//GEN-HEADEREND:event_Menu_File_OpenActionPerformed
        String path=JOptionPane.showInputDialog(this,"Dateiname:","Datei öffnen",JOptionPane.QUESTION_MESSAGE);
        try
        {
            FileReader file=new FileReader(path);
            BufferedReader reader=new BufferedReader(file);
            DefaultTableModel model=(DefaultTableModel)this.Table.getModel();
            String str;
            while((str=reader.readLine())!=null)
            {
                String[] parts=str.split(";");
                if(parts.length==2)
                {
                    model.addRow(new Object[]
                    {
                        parts[0],parts[1]
                    });
                }
            }
            reader.close();
            file.close();
        }
        catch(FileNotFoundException ex1)
        {
            JOptionPane.showConfirmDialog(this,"Datei nicht gefunden!","Fehler",JOptionPane.DEFAULT_OPTION);
        }
        catch(IOException ex2)
        {
            JOptionPane.showConfirmDialog(this,"IOException!","Fehler",JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_Menu_File_OpenActionPerformed

    private void Menu_File_SaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Menu_File_SaveActionPerformed
    {//GEN-HEADEREND:event_Menu_File_SaveActionPerformed
        DefaultTableModel model=(DefaultTableModel)this.Table.getModel();
        ArrayList<Row> list=new ArrayList();
        for(int i=0;i<model.getRowCount();i++)
        {
            list.add(new Row((String)model.getValueAt(i,0),(String)model.getValueAt(i,1)));
        }

        String path=JOptionPane.showInputDialog(this,"Dateiname:","Datei öffnen",JOptionPane.QUESTION_MESSAGE);

        try
        {
            FileWriter writer=new FileWriter(new File(path));
            for(Object obj:list.toArray())
            {
                writer.write(((Row)obj).toString()+'\n');
            }
            writer.flush();
            writer.close();
        }
        catch(IOException ex)
        {
            JOptionPane.showConfirmDialog(this,"IOException!","Fehler",JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_Menu_File_SaveActionPerformed

    private void Menu_Vocab_AddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Menu_Vocab_AddActionPerformed
    {//GEN-HEADEREND:event_Menu_Vocab_AddActionPerformed
        new VocabDialog(this,false).setVisible(true);
    }//GEN-LAST:event_Menu_Vocab_AddActionPerformed

    public void add(VocabDialog dialog)
    {
        DefaultTableModel model=(DefaultTableModel)this.Table.getModel();
        String de=dialog.de;
        String en=dialog.en;
        model.addRow(new Object[]
        {
            en,de
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Fenster.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Fenster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem Menu_File_Open;
    private javax.swing.JMenuItem Menu_File_Save;
    private javax.swing.JMenuItem Menu_Vocab_Add;
    private javax.swing.JPanel Panel;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
