/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.benary.vocab;

/**
 *
 * @author benaryorg
 */
public class VocabDialog extends javax.swing.JDialog
{

    protected String en;
    protected String de;
    protected Fenster parent;

    /**
     * Creates new form to enter a new Word
     *
     * @param parent The Parent of the VocabDialog Object
     * @param modal To be honest…. I have no Idea
     */
    public VocabDialog(Fenster parent,boolean modal)
    {
        super(parent,modal);
        this.parent=parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Text_English1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Text_German1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hinzufügen");
        setMinimumSize(new java.awt.Dimension(240, 128));

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        jLabel3.setText("English:");
        jPanel1.add(jLabel3);

        Text_English1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Text_English1ActionPerformed(evt);
            }
        });
        jPanel1.add(Text_English1);

        jLabel4.setText("German:");
        jPanel1.add(jLabel4);

        Text_German1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                Text_German1ActionPerformed(evt);
            }
        });
        jPanel1.add(Text_German1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Text_German1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Text_German1ActionPerformed
    {//GEN-HEADEREND:event_Text_German1ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_Text_German1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        this.de=this.Text_German1.getText();
        this.en=this.Text_English1.getText();
        this.parent.add(this);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Text_English1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_Text_English1ActionPerformed
    {//GEN-HEADEREND:event_Text_English1ActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_Text_English1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(VocabDialog.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(VocabDialog.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(VocabDialog.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(VocabDialog.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Text_English1;
    private javax.swing.JTextField Text_German1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
