/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.benary.vocab.Checks;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.benary.vocab.Main;
import org.benary.vocab.Window;

/**
 *
 * @author benaryorg
 */
public class Single extends javax.swing.JFrame
{

    public final Random rand;
    private final Window window;
    private final JTable table;
    private final DefaultTableModel model;
    private int right;
    private int wrong;

    /**
     *
     * @param window The Root Window
     */
    public Single(Window window)
    {
        Single.main(new String[]
        {
        });
        this.rand=Main.rand;
        this.window=window;
        this.table=this.window.Table;
        this.model=(DefaultTableModel)this.table.getModel();
        initComponents();
        checkNewWord();
    }

    public final void checkNewWord()
    {
        int count=this.model.getRowCount();
        int row=rand.nextInt(count);
        this.jLabel1.setText((String)model.getValueAt(row,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        Submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Check your Vocab!");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Erstes Deutsches Wort");
        getContentPane().add(jLabel1);

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);

        jPanel1.setLayout(new java.awt.GridLayout(0, 2));

        Submit.setText("Prüfen");
        Submit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);

        Cancel.setText("Abbrechen");
        Cancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jTextField1ActionPerformed
    {//GEN-HEADEREND:event_jTextField1ActionPerformed
        SubmitActionPerformed(evt);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SubmitActionPerformed
    {//GEN-HEADEREND:event_SubmitActionPerformed
		String de=this.jLabel1.getText();
        this.jLabel1.setText("");
        String en=this.jTextField1.getText();
        this.jTextField1.setText("");
        JTable table=this.window.Table;
        DefaultTableModel model=(DefaultTableModel)table.getModel();
        for(int i=0;i<table.getRowCount();i++)
        {
            if(((String)model.getValueAt(i,1)).equals(de))
            {
				boolean found=false;
                String _str[]=((String)model.getValueAt(i,0)).split("#");
				for(String str:_str)
				{
					if(str.trim().equals(en))
					{
						found=true;
					}
				}
                if(found)
                {
                    this.right++;
                }
                else
                {
                    this.wrong++;
                    JOptionPane.showConfirmDialog(this,"Falsch!\nEs wäre \""+(_str.length<=1?_str[0]:((String)model.getValueAt(i,0)).replace("#","\" oder \""))+"\" gewesen!","Falsch!",JOptionPane.DEFAULT_OPTION);
					break;
                }
            }
        }
        this.setTitle("Score: "+this.right+"/"+this.wrong+"="+String.format("%.3f",(float)this.right/(double)this.wrong));
        this.checkNewWord();
    }//GEN-LAST:event_SubmitActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CancelActionPerformed
    {//GEN-HEADEREND:event_CancelActionPerformed
        this.dispose();
        this.window.setVisible(true);
    }//GEN-LAST:event_CancelActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        CancelActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for(javax.swing.UIManager.LookAndFeelInfo info:javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Single.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Single.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Single.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Single.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        //</editor-fold>
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
